export const CARD_TYPE = {
  PERSON:    'PERSON',
  WARRIOR:   'WARRIOR',
  ARCHER:    'ARCHER',
  SCOUT:     'SCOUT',
  ROCK:      'ROCK',
  TREE:      'TREE',
  WOLF:      'WOLF',
  BEAR:      'BEAR',
  FOOD:      'FOOD',
  SEED:      'SEED',
  STONE:     'STONE',
  WOOD:      'WOOD',
  SPEAR:     'SPEAR',
  BOW:       'BOW',
  BOAT:      'BOAT',
  BRICK:     'BRICK',
  WALL:      'WALL',
  FARMLAND:  'FARMLAND',
  ORCHARD:   'ORCHARD',
  LOG_HOUSE: 'LOG_HOUSE',
  VILLAGE:   'VILLAGE',
  CITY:      'CITY',
  RAIDER:    'RAIDER',
  CATAPULT:  'CATAPULT',
};

export const CARD_META = {
  [CARD_TYPE.PERSON]:    { label: '사람',      icon: '👤', category: 'human' },
  [CARD_TYPE.WARRIOR]:   { label: '전사',      icon: '⚔️',  category: 'human' },
  [CARD_TYPE.ARCHER]:    { label: '궁수',      icon: '🏹', category: 'human' },
  [CARD_TYPE.SCOUT]:     { label: '척후병',    icon: '🔭', category: 'human' },
  [CARD_TYPE.ROCK]:      { label: '바위',      icon: '⛰️',  category: 'nature' },
  [CARD_TYPE.TREE]:      { label: '나무',      icon: '🌲', category: 'nature' },
  [CARD_TYPE.WOLF]:      { label: '늑대',      icon: '🐺', category: 'threat' },
  [CARD_TYPE.BEAR]:      { label: '곰',        icon: '🐻', category: 'threat' },
  [CARD_TYPE.FOOD]:      { label: '식량',      icon: '🍖', category: 'resource' },
  [CARD_TYPE.SEED]:      { label: '씨앗',      icon: '🌱', category: 'resource' },
  [CARD_TYPE.STONE]:     { label: '돌',        icon: '🪨', category: 'resource' },
  [CARD_TYPE.WOOD]:      { label: '목재',      icon: '🪵', category: 'resource' },
  [CARD_TYPE.SPEAR]:     { label: '창',        icon: '🗡️',  category: 'weapon' },
  [CARD_TYPE.BOW]:       { label: '활',        icon: '🏹', category: 'weapon' },
  [CARD_TYPE.BOAT]:      { label: '배',        icon: '⛵', category: 'resource' },
  [CARD_TYPE.BRICK]:     { label: '벽돌',      icon: '🧱', category: 'resource' },
  [CARD_TYPE.WALL]:      { label: '성벽',      icon: '🏰', category: 'building' },
  [CARD_TYPE.FARMLAND]:  { label: '농지',      icon: '🌾', category: 'building' },
  [CARD_TYPE.ORCHARD]:   { label: '과수원',    icon: '🍎', category: 'building' },
  [CARD_TYPE.LOG_HOUSE]: { label: '목조 가옥', icon: '🏠', category: 'building' },
  [CARD_TYPE.VILLAGE]:   { label: '마을',      icon: '🏘️', category: 'building' },
  [CARD_TYPE.CITY]:      { label: '도시',      icon: '🏙️',  category: 'building' },
  [CARD_TYPE.RAIDER]:    { label: '약탈자',    icon: '🗡️',  category: 'enemy' },
  [CARD_TYPE.CATAPULT]:  { label: '투석기',    icon: '⚙️',  category: 'enemy' },
};
